Gemfile.lock

Changing: rubyracer (and dependencies), mysql2 gem versions

Reverted Gemfile.lock to the previous commit.

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/codemirror_barcodes.js
app/assets/javascripts/scans.coffee
app/assets/stylesheets/application.css
app/assets/stylesheets/form.css.scss
app/views/scans/_form.html.erb
spec/features/scans_spec.rb

Closes GPL461
* Add a editor to display the scanned barcodes with the line numbers
* Display duplicated barcodes in red inside the editor

Gpl461 add plate count

---

app/models/manifest_uploader.rb

try explicitly requiring csv
- not sure why this is only an issue in UAT, not local

GPL-468 fix

---

app/forms/upload_labware_form.rb
spec/forms/upload_labware_form_spec.rb

Add file type to error message to aid debugging in UAT

GPL-468 fix 3

---

app/forms/upload_labware_form.rb
spec/features/upload_labware_spec.rb
spec/forms/upload_labware_form_spec.rb

Check file type using extension rather than mime type
- Files Danni produced on her laptop (Windows) seemed to still have an excel mime type rather than csv

GPL-468 fix (again)

---

app/forms/location_form.rb
lib/tasks/duplicate_labware_data_fix.rake
spec/forms/location_form_spec.rb

Develop into Master

---

Gemfile
Gemfile.lock
config/initializers/cors.rb

Added cors support.

---

app/views/application/_location.html.erb
spec/features/locations_spec.rb

GPL587 - Added barcode to information window

---

app/models/manifest_uploader.rb
app/views/upload_labware/_form.html.erb
spec/factories/csv_manifest.rb
spec/models/manifest_uploader_spec.rb

Gpl 627 upload labware positions

---

app/models/locations/ordered_location.rb
spec/forms/location_form_spec.rb
spec/models/locations/ordered_location_spec.rb

Fix ordered location deletion

---

app/models/event.rb

tweak comments - hopefully easier to understand

GPL-756 fix

---

app/forms/move_location_form.rb
spec/forms/move_location_form_spec.rb

Added audit record creation for labwares that have been moved.

---

app/assets/javascripts/scans.coffee
app/views/move_locations/_form.html.erb
spec/features/move_locations_spec.rb
spec/features/scans_spec.rb
spec/rails_helper.rb
spec/support/shared_helpers.rb

and refactored out now shared test helper method
closes #282

Added duplicate location barcode ui validation to Move Locations,

---

app/forms/move_location_form.rb
app/lib/location_creator.rb
lib/tasks/location_creator.rake
spec/forms/move_location_form_spec.rb

GPL-798 - Prevent parent location from being a building for move locations

---

app/controllers/location_finder_controller.rb
app/forms/location_finder_form.rb
app/forms/upload_labware_form.rb
app/lib/validators/csv_file_validator.rb
app/models/labware.rb
app/models/location_finder.rb
app/null_objects/null_labware.rb
app/null_objects/null_location.rb
app/views/application/_nav.html.erb
app/views/location_finder/_form.html.erb
app/views/location_finder/create.html.erb
app/views/location_finder/new.html.erb
config/routes.rb
spec/features/location_finder_spec.rb
spec/features/upload_labware_spec.rb
spec/forms/location_finder_form_spec.rb
spec/models/labware_spec.rb
spec/models/location_finder_spec.rb
spec/rails_helper.rb
spec/support/helpers.rb

Gpl 809 find location of all plates in single operation

---

app/models/users/user.rb
lib/tasks/hash_user_swipe_cards.rake
spec/api/location_types_spec.rb
spec/api/locations_spec.rb
spec/api/scans_spec.rb
spec/factories/sequences.rb
spec/factories/users.rb
spec/features/empty_locations_spec.rb
spec/features/locations_spec.rb
spec/features/move_locations_spec.rb
spec/features/scans_spec.rb
spec/features/teams_spec.rb
spec/features/upload_labware_spec.rb
spec/features/users_spec.rb
spec/forms/auditor_spec.rb
spec/forms/authentication_form_spec.rb
spec/forms/empty_location_form_spec.rb
spec/forms/move_location_form_spec.rb
spec/forms/scan_form_spec.rb
spec/forms/user_form_spec.rb
spec/models/user_spec.rb

Closes #312 
*Swipe card now hashed on creation
*
* ...
Testing needs thinking about

GPL-814-1 added encryption to swipe card, fixed tests

---

app/forms/user_form.rb
app/models/users/guest.rb
app/models/users/user.rb
app/views/users/_form.html.erb
spec/features/users_spec.rb
spec/forms/user_form_spec.rb

GPL-849 Bug on updating user

---

.rubocop.yml
app/forms/user_form.rb
app/models/users/guest.rb
app/models/users/user.rb
app/views/users/_form.html.erb
spec/features/users_spec.rb
spec/forms/user_form_spec.rb

Closes #
*This change has been UAT'd from branch GPL-831
*Now merging into develop to then merge into master and deploy to prod
* ...

Bug on updating user

---

.github/workflows/build.yml

renamed asset form gh-release to release

---

README.md
lib/tasks/restriction_creator.rake

updated restrictions rake task

---

.github/workflows/asset_dispatch.yml
.github/workflows/automated_release_and_build.yml

fixed yaml syntax error

---

app/messages/messages/broker.rb
spec/messages/broker_spec.rb

Removed queue from bunny config.

---

.github/workflows/asset_dispatch.yml
.github/workflows/automated_release_and_build.yml
.github/workflows/check_release_version.yml

Part of https://github.com/sanger/deployment/issues/71

DPL-083 Update GitHub workflows to assist in automated release versioning

---

.github/workflows/automated_release_and_build.yml
.github/workflows/ruby.yml

Updated actions.

---

Gemfile

Move js gems to development group

---

spec/features/teams_spec.rb

Add a wait. See if it makes any difference.

---

spec/features/locations_spec.rb
spec/rails_helper.rb

Add change to root.join

---

Gemfile.lock

Added amr-64 to gemfile lock.

---

README.md
lib/tasks/db.rake

Closes #
- Improvements to the readme
- Fix bug in dummy data rake task

Setup improvements

---

.github/workflows/add_to_tech_debt_project.yml

Closes #
- first attempt at workflow to add depfu PRs to technical debt project

Draft workflow to add depfu PRs to technical debt project

---

.github/workflows/add_to_tech_debt_project.yml

fix indentation and try a new path to workflow

---

.github/workflows/add_to_tech_debt_project.yml

GitHub action add to tech debt project

---

.github/workflows/add_to_tech_debt_project.yml

- remove 'with' as I don't think it was working
Closes #
- 

rename the secret to be simpler

---

Gemfile.lock
app/models/locations/location.rb
lib/tasks/destroyed_location.rake
spec/lib/tasks/destroyed_location_spec.rb
spec/models/locations/location_spec.rb

Closes #
- Add rake task to create the Destroyed Location Type and the Location
I have left the existing Destroyed locations intact in this PR. They will be coordinated with stakeholders.

Dpl 310 destruction feature to move labware to labwhere destroyed location

---

.rubocop.yml
app/forms/location_finder_form.rb
app/lib/validators/csv_file_validator.rb
app/views/location_finder/_form.html.erb
app/views/location_finder/create.html.erb
spec/forms/location_finder_form_spec.rb

Closes #827 
- Changes location finder to access `file` param safely.
- Makes file input a required field for form submission.

Y24-288 - Location finder bug

---

.github/workflows/asset_dispatch.yml
.github/workflows/automated_release_and_build.yml
.github/workflows/check_release_name_bump.yml
.github/workflows/check_release_version.yml
.github/workflows/ruby.yml

Closes https://github.com/sanger/General-Backlog-Items/issues/433
- Bumped `checkout` dependency to v4.

Y24-244 - Update checkout dependency to v4
